# Generated by Django 4.2.21 on 2025-07-05 18:18

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this activity', primary_key=True, serialize=False)),
                ('marketplace_id', models.CharField(help_text='Amazon marketplace ID (e.g., ATVPDKIKX0DER for US)', max_length=255)),
                ('activity_type', models.CharField(choices=[('fetch', 'Data Fetch'), ('sync', 'Data Sync')], default='fetch', help_text='Type of activity performed', max_length=50)),
                ('activity_date', models.DateTimeField(auto_now_add=True, help_text='When this activity was initiated')),
                ('date_from', models.DateField(help_text='Start date for data range')),
                ('date_to', models.DateField(help_text='End date for data range')),
                ('action', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', help_text='How this activity was triggered', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the activity', max_length=50)),
                ('orders_fetched', models.PositiveIntegerField(default=0, help_text='Number of orders successfully fetched', validators=[django.core.validators.MinValueValidator(0)])),
                ('items_fetched', models.PositiveIntegerField(default=0, help_text='Number of order items successfully fetched', validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_seconds', models.FloatField(blank=True, help_text='Total time taken for the activity in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('detail', models.TextField(blank=True, default='', help_text='User-friendly description of the activity status or any errors')),
                ('error_message', models.TextField(blank=True, help_text='Technical error message if the activity failed', null=True)),
                ('database_saved', models.BooleanField(default=False, help_text='Whether the processed data was saved to databases (MSSQL and Azure)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['marketplace_id', '-activity_date'], name='api_activit_marketp_a3a945_idx'), models.Index(fields=['activity_type', '-activity_date'], name='api_activit_activit_989173_idx'), models.Index(fields=['status', '-activity_date'], name='api_activit_status_dfae75_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='activities',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('marketplace_id', 'activity_type', 'date_from', 'date_to', 'status'), name='unique_in_progress_activity'),
        ),
    ]
