# Generated by Django 4.2.21 on 2025-06-23 14:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketplace_id', models.CharField(help_text='Amazon marketplace ID', max_length=50)),
                ('marketplace_name', models.CharField(blank=True, help_text='Human readable marketplace name', max_length=100)),
                ('activity_type', models.CharField(choices=[('fetch', 'Data Fetch'), ('export', 'Data Export'), ('process', 'Data Processing')], default='fetch', help_text='Type of activity performed', max_length=20)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the activity was performed')),
                ('activity_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled')], default='in_progress', help_text='Current status of the activity', max_length=20)),
                ('date_from', models.DateField(help_text='Start date for data fetch')),
                ('date_to', models.DateField(help_text='End date for data fetch')),
                ('action', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('scheduled', 'Scheduled')], default='manual', help_text='How the activity was triggered', max_length=20)),
                ('orders_fetched', models.IntegerField(default=0, help_text='Total number of orders fetched')),
                ('items_fetched', models.IntegerField(default=0, help_text='Total number of order items fetched')),
                ('duration_seconds', models.FloatField(blank=True, help_text='How long the activity took in seconds', null=True)),
                ('detail', models.TextField(blank=True, help_text='User-friendly success or failure message')),
                ('error_message', models.TextField(blank=True, help_text='Technical error details if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['marketplace_id'], name='api_activit_marketp_f2d9d5_idx'), models.Index(fields=['activity_type'], name='api_activit_activit_830180_idx'), models.Index(fields=['activity_status'], name='api_activit_activit_5d8332_idx'), models.Index(fields=['activity_date'], name='api_activit_activit_c770c5_idx')],
            },
        ),
    ]
