# Generated by Django 4.2.21 on 2025-06-24 12:46

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activities',
            name='api_activit_marketp_f2d9d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='activities',
            name='api_activit_activit_830180_idx',
        ),
        migrations.RemoveIndex(
            model_name='activities',
            name='api_activit_activit_5d8332_idx',
        ),
        migrations.RemoveIndex(
            model_name='activities',
            name='api_activit_activit_c770c5_idx',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='activity_status',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='marketplace_name',
        ),
        migrations.AddField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the activity', max_length=50),
        ),
        migrations.AlterField(
            model_name='activities',
            name='action',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('automatic', 'Automatic')], default='manual', help_text='How this activity was triggered', max_length=50),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When this activity was initiated'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this activity', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('fetch', 'Data Fetch'), ('export', 'Data Export'), ('sync', 'Data Sync')], default='fetch', help_text='Type of activity performed', max_length=50),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_from',
            field=models.DateField(help_text='Start date for data range'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date_to',
            field=models.DateField(help_text='End date for data range'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='detail',
            field=models.TextField(blank=True, default='', help_text='User-friendly description of the activity status or any errors'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='duration_seconds',
            field=models.FloatField(blank=True, help_text='Total time taken for the activity in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activities',
            name='error_message',
            field=models.TextField(blank=True, help_text='Technical error message if the activity failed', null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='items_fetched',
            field=models.PositiveIntegerField(default=0, help_text='Number of order items successfully fetched', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activities',
            name='marketplace_id',
            field=models.CharField(help_text='Amazon marketplace ID (e.g., ATVPDKIKX0DER for US)', max_length=255),
        ),
        migrations.AlterField(
            model_name='activities',
            name='orders_fetched',
            field=models.PositiveIntegerField(default=0, help_text='Number of orders successfully fetched', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='activities',
            index=models.Index(fields=['marketplace_id', '-activity_date'], name='api_activit_marketp_a3a945_idx'),
        ),
        migrations.AddIndex(
            model_name='activities',
            index=models.Index(fields=['activity_type', '-activity_date'], name='api_activit_activit_989173_idx'),
        ),
        migrations.AddIndex(
            model_name='activities',
            index=models.Index(fields=['status', '-activity_date'], name='api_activit_status_dfae75_idx'),
        ),
    ]
