# Generated by Django 4.2.21 on 2025-07-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceLastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_id', models.CharField(max_length=255)),
                ('last_run', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marketplace Last Run',
                'verbose_name_plural': 'Marketplace Last Runs',
                'db_table': 'marketplace_last_run',
            },
        ),
    ]
