# Generated by Django 4.2.21 on 2025-06-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_activities_api_activit_marketp_f2d9d5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='database_saved',
            field=models.BooleanField(default=False, help_text='Whether the processed data was saved to databases (MSSQL and Azure)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='action',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', help_text='How this activity was triggered', max_length=50),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('fetch', 'Data Fetch'), ('sync', 'Data Sync')], default='fetch', help_text='Type of activity performed', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='activities',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('marketplace_id', 'activity_type', 'date_from', 'date_to', 'status'), name='unique_in_progress_activity'),
        ),
    ]
