# Generated by Django 4.2.21 on 2025-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activities_database_saved_alter_activities_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('fetching', 'Fetching Job'), ('syncing', 'Syncing Job')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('cron_expression', models.CharField(help_text="Cron expression (e.g., '0 0 */15 * *')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_range_days', models.IntegerField(default=15, help_text='Number of days to fetch (for fetching job)')),
                ('sync_days_back', models.IntegerField(default=100, help_text='Number of days back to sync (for syncing job)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cron Job Configuration',
                'verbose_name_plural': 'Cron Job Configurations',
                'db_table': 'cron_job_configuration',
            },
        ),
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('task_id', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('records_processed', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Cron Job Log',
                'verbose_name_plural': 'Cron Job Logs',
                'db_table': 'cron_job_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CronJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('fetching', 'Fetching Job'), ('syncing', 'Syncing Job')], max_length=20, unique=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_duration', models.DurationField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cron Job Status',
                'verbose_name_plural': 'Cron Job Statuses',
                'db_table': 'cron_job_status',
            },
        ),
    ]
