# Generated by Django 4.2.21 on 2025-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cronjobconfiguration_cronjobexecution_cronjobstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='azure_saved',
            field=models.BooleanField(default=False, help_text='Whether the processed data was saved to Azure database'),
        ),
        migrations.AddField(
            model_name='activities',
            name='mssql_saved',
            field=models.BooleanField(default=False, help_text='Whether the processed data was saved to MSSQL database'),
        ),
    ]
