# Generated by Django 4.2.21 on 2025-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activities_azure_saved_activities_mssql_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjobexecution',
            name='cron_job',
        ),
        migrations.RemoveField(
            model_name='cronjoblog',
            name='execution',
        ),
        migrations.AlterUniqueTogether(
            name='cronjobstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cronjobstats',
            name='cron_job',
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('fetch orders', 'Data Fetch'), ('fetch reports', 'Reports Fetch'), ('sync orders', 'Data Sync')], default='fetch orders', help_text='Type of activity performed', max_length=50),
        ),
        migrations.DeleteModel(
            name='CronJobConfiguration',
        ),
        migrations.DeleteModel(
            name='CronJobExecution',
        ),
        migrations.DeleteModel(
            name='CronJobLog',
        ),
        migrations.DeleteModel(
            name='CronJobStats',
        ),
    ]
