# Generated by Django 4.2.21 on 2025-08-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cronjobexecution_cron_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.CharField(choices=[('orders', 'Data Fetch'), ('reports', 'Reports Fetch'), ('sync', 'Data Sync')], default='fetch orders', help_text='Type of activity performed', max_length=50),
        ),
    ]
