# Generated by Django 4.2.21 on 2026-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_activities_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCMLastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_id', models.CharField(help_text='Amazon marketplace ID (e.g., ATVPDKIKX0DER for US)', max_length=255, unique=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='Last successful fetch date/time for this marketplace', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SCM Last Run',
                'verbose_name_plural': 'SCM Last Runs',
                'db_table': 'scm_last_run',
            },
        ),
    ]
