# Generated by Django 4.2.21 on 2026-03-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_company_name_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activities',
            new_name='api_activit_company_bf92b9_idx',
            old_name='api_activit_company_619236_idx',
        ),
    ]
