# Generated by Django 4.2.21 on 2026-04-09 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_api_activit_company_619236_idx_api_activit_company_bf92b9_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups all marketplace results belonging to the same scheduled run')),
                ('marketplace_code', models.CharField(help_text='Short marketplace code, e.g. UK, US, IT', max_length=10)),
                ('marketplace_id', models.CharField(blank=True, default='', help_text='Amazon marketplace ID', max_length=255)),
                ('marketplace_name', models.CharField(blank=True, default='', help_text='Human-readable marketplace name', max_length=100)),
                ('credential_group', models.CharField(blank=True, default='', help_text='Credential group used for authentication', max_length=100)),
                ('report_id', models.CharField(blank=True, default='', help_text='Amazon report ID fetched', max_length=255)),
                ('report_date', models.DateField(help_text='The date the inventory report covers (typically yesterday)')),
                ('items_count', models.PositiveIntegerField(default=0, help_text='Number of inventory items in the report')),
                ('file_path', models.CharField(blank=True, default='', help_text='Local file path where the report CSV was saved', max_length=500)),
                ('mssql_saved', models.BooleanField(default=False)),
                ('azure_saved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='schedule', help_text='How the run was triggered: schedule, manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Report Log',
                'verbose_name_plural': 'Inventory Report Logs',
                'db_table': 'inventory_report_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run_id'], name='inventory_r_run_id_956dde_idx'), models.Index(fields=['marketplace_code', '-created_at'], name='inventory_r_marketp_3963d5_idx'), models.Index(fields=['status', '-created_at'], name='inventory_r_status_6807cc_idx'), models.Index(fields=['report_date'], name='inventory_r_report__b9e45b_idx')],
            },
        ),
    ]
